# SOLVE OPTIONS
solve:
    mode: quantity  # price, quantity
    phase: MT  # LT, MT
    solver: coin  # coin, glpk, xpress, gurobi    
    cat: Integer # Integer, Binary or Continuous
    scenario: Base
    allow_use: 1  # allow unserved energy
    allow_dump: 1  # allow dump energy	
    include_ramps: 0  # consider max ramp up limits
    include_msl: 1  # consider min stable level
    include_no_load_costs: 1 # consider no load costs
    include_start_costs: 1  # consider start costs	
    epgap: 0.0001  # mipgap tolerance termination
    sec: 7200
    
# TIME OPTIONS
time:
    stepsize: 24
    blocks: 3


# OUTPUT OPTIONS
output:
    verbose: 0 # amount of progress info printed
    out_csv: 1 # write csv files
    out_lp: 0  # write LP file
    out_mps: 0  #write MPS file        

# MODEL SCALARS
scalars:
    discountrate: 0
    thermalfirm: 1
    hydrofirm: 1
    capacityindex: -1
    buildub: 0
    voll: 75000
    pricedumpenergy: 5000
    ptyminhflow: 10000
    ptymaxhflow: 10000
    ptyminvol: 10000
    loadescalator: 1
    branchescalator: 1

# COMPONENT PARAMETERS
generator:
    units: 0
    max build: 0
    max capacity: 0
    msl: 0
    forced outage rate: 0
    vom: 0
    heat rate: 0
    start up: 0
    annuity: 0
    ramp up: 1e+20
    no load: 0
    derating: 1   # multiplier
    efficiency: 0
    inflow: 0
    
bus:
    load: 0
    
branch:
    max flow: 0
    
fuel:
    price: 0